[package]
name = "orml-oracle-rpc"
version = "0.0.1"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.2.0" }
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
sp-runtime = { version = "2.0.0-alpha.3" }
sp-api = { version = "2.0.0-alpha.3" }
sp-blockchain = { version = "2.0.0-alpha.3" }
orml-oracle-rpc-runtime-api = { path = "runtime-api" }
