[package]
name = "orml-oracle-rpc-runtime-api"
version = "0.1.0"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.6", default-features = false, features = ["derive"] }
sp-api = { version = "2.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git" }

[features]
default = ["std"]
std = [
	"sp-api/std",
	"codec/std",
]
